version: '3'

services:
  backend:
    build: ./ktor-backend
    networks:
      - web
    expose:
      - 5000
    environment:
      - DB_HOST=database
      - DB_PASSWORD=schueler
    restart: unless-stopped
  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile
    networks:
      - web
    ports:
      - 1337:80
    depends_on:
      - backend
    environment:
      - VIRTUAL_HOST=wls.byleo.net
      - LETSENCRYPT_HOST=wls.byleo.net
      - VIRTUAL_PORT=80
    restart: unless-stopped

networks:
  web:
    external: true
